version: '2'
services:
  gongkou:
    container_name: gongkou
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myapp/src
      - ./out:/myapp/out
      - ./gongkou.sh:/myapp/gongkou.sh
    command: /bin/sh -c "tsc && sh ./gongkou.sh"
